// Run the supplied Python validator unchanged against positive/negative controls
// and outputs generated by PhyloScope. Requires Python with ete3 installed.
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");
const { spawnSync } = require("node:child_process");
const assert = require("node:assert/strict");
const { harness } = require("./helpers.cjs");
const { fixtureDir, families, fixtureTarget } = require("./reroot-helpers.cjs");

async function main() {
  const outputDir = fs.mkdtempSync(path.join(os.tmpdir(), "phyloscope-reroot-"));
  console.log(`Outputs and validator logs: ${outputDir}`);
  const python = process.env.PHYLOSCOPE_PYTHON || "python";
  function validate(family, label, output, expectedStatus = 0) {
    const result = spawnSync(python, [
      path.join(fixtureDir, "validate_reroot.py"),
      path.join(fixtureDir, `${family}.input.nwk`), output,
      "--outgroup-ref", path.join(fixtureDir, `${family}.outgroup_ref.nwk`),
    ], { encoding: "utf8" });
    if (result.error) throw result.error;
    const log = result.stdout + result.stderr;
    fs.writeFileSync(path.join(outputDir, `${family}.${label}.log.txt`), log);
    assert.equal(result.status, expectedStatus, log);
    if (expectedStatus === 0) {
      assert.match(log, /RESULT: PASS \(8\/8 checks passed\)/);
    } else {
      assert.match(log, /RESULT: FAIL \(4\/8 checks passed\)/);
      assert.deepEqual([...log.matchAll(/\[FAIL\] (\d+)\./g)].map(match => Number(match[1])), [4, 6, 7, 8]);
    }
    console.log(`${family} ${label}: ${log.match(/RESULT: .*/)[0]}, exit ${result.status}`);
  }

  // Controls must run before accepting any result produced by the application.
  for (const family of families) validate(family.name, "expected", path.join(fixtureDir, `${family.name}.expected.nwk`));
  validate("AT3G05360.1_RLP", "buggy", path.join(fixtureDir, "AT3G05360.1_RLP.buggy.nwk"), 1);

  const h = await harness();
  const { parseNewick } = await h.load("parsers");
  const { rerootTree, nodeToNewick } = await h.load("tree-ops");
  for (const family of families) {
    const { tree, target } = fixtureTarget(parseNewick, family.name);
    const output = path.join(outputDir, `${family.name}.phyloscope.nwk`);
    fs.writeFileSync(output, nodeToNewick(rerootTree(tree, target.id)) + ";");
    validate(family.name, "phyloscope", output);
  }
}

main().catch(error => { console.error(error); process.exitCode = 1; });
